In [2]:
import geopandas as gpd
import pandas as pd
import numpy as np
import os
from osgeo import gdal

In [26]:
os.getcwd()

'd:\\Rubel\\M.Tech\\MTP\\Phase 2'

In [34]:
df1 = gpd.read_file('Glacial_Lake_Inventory\GlacialLake_20220726\GlacialLake_1990.shp')
df1.shape

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\1449604399.py:1: SyntaxWarning: invalid escape sequence '\G'
  df1 = gpd.read_file('Glacial_Lake_Inventory\GlacialLake_20220726\GlacialLake_1990.shp')

(7334, 13)

In [35]:
def create_df(folder_path):
  i = 1
  for file in os.listdir(folder_path):
    if file.endswith('.shp'):
      full_path = os.path.join(folder_path,file)
      globals()[f'df{i}'] = gpd.read_file(full_path)
      i += 1


create_df('Glacial_Lake_Inventory\GlacialLake_20220726')

<>:10: SyntaxWarning: invalid escape sequence '\G'
<>:10: SyntaxWarning: invalid escape sequence '\G'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\2128150823.py:10: SyntaxWarning: invalid escape sequence '\G'
  create_df('Glacial_Lake_Inventory\GlacialLake_20220726')

In [36]:
df1.keys()

Index(['Id', 'Date', 'PR', 'Type', 'Perimeter', 'Area', 'Region', 'Error',
       'Not_RGI', 'Elevation', 'MG_ID1', 'MG_ID2', 'geometry'],
      dtype='str')

In [45]:
df5.iloc[7]

Source                                    p147r036_lc820201014
Date                                                2020/10/14
Area                                                  0.074128
Region                                               Karakoram
Type                                         Pro-glacial lakes
Not_RGI                                                    NaN
Error                                                 0.015697
Perimeter                                          1046.494224
Elevation                                                 5392
MG_ID1                                          RGI60-14.09028
MG_ID2                                                     NaN
NewPro                                                     NaN
geometry     POLYGON ((-1425484.4206890615 651570.283769733...
Name: 7, dtype: object

In [30]:
glof_df = gpd.read_file('model_data\shapefiles\glofs\glof.shp')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\2283591598.py:1: SyntaxWarning: invalid escape sequence '\s'
  glof_df = gpd.read_file('model_data\shapefiles\glofs\glof.shp')

In [31]:
glof_df

,id,gf_id,ID_1,date,final_lat,final_lon,elev_lake,lake_name,glacier_na,final_geom,geometry
0,1,271.0,NaN,1975-08-18,43.039000,77.044000,3460.0,Ozernaya,Sovetov,POINT (77.044 43.03900000000001),POINT (77.044 43.039)
1,2,273.0,292.0,1976-06-18,35.677371,77.190788,4880.0,Kyagar,Kyagar,POINT (77.190788 35.67737100000001),POINT (77.19079 35.67737)
2,3,274.0,NaN,1976-06-24,43.031261,77.113936,3590.0,Sol Talgar,Unnamed,POINT (77.113936 43.03126099999999),POINT (77.11394 43.03126)
3,4,NaN,307.0,1977-07-16,35.677413,77.193246,NaN,NaN,NaN,POINT (77.193246 35.677413000000016),POINT (77.19325 35.67741)
4,5,286.0,NaN,1977-08-01,35.677371,77.190788,4880.0,Kyagar,Kyagar,POINT (77.190788 35.67737100000001),POINT (77.19079 35.67737)
...,...,...,...,...,...,...,...,...,...,...,...
110,112,753.0,NaN,2024-04-21,28.596901,84.631217,3637.0,Birendra Taal,Manaslu,POINT (84.631217 28.596900999999995),POINT (84.63122 28.5969)
111,113,756.0,NaN,2024-08-16,27.826109,86.570105,4900.0,Upper Ngole Cho,Thyangbo,POINT (86.570105 27.82610899999999),POINT (86.5701 27.82611)
112,114,757.0,NaN,2024-08-16,27.826109,86.570105,4800.0,Lower Ngole Cho,Thyangbo,POINT (86.570105 27.82610899999999),POINT (86.5701 27.82611)
113,115,758.0,NaN,2024-08-30,35.780972,72.175989,4200.0,Shahzore,Shahzore,POINT (72.175989 35.780971999999984),POINT (72.17599 35.78097)
114,116,759.0,NaN,2025-06-13,35.490815,69.444956,4197.0,Taghanak,Unnamed,POINT (69.444956 35.490815000000005),POINT (69.44496 35.49082)

In [ ]:
gdf_2015 = gpd.read_file('glacier_lake\glacier lake data-submitted\High_Asia_glacial_lake_2015.shp')
gdf_2018.head(2)

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\2579756489.py:1: SyntaxWarning: invalid escape sequence '\g'
  gdf_2018 = gpd.read_file('glacier_lake\glacier lake data-submitted\High_Asia_glacial_lake_2018.shp')

,OBJECTID,GLAKE_ID,GL_Image,GL_Type,GL_SubR,GL_Time,GL_Elev,GL_Area,GL_Peri,GL_A_Error,GL_Long,GL_Lati,geometry
0,1,GL098735E52534N,LC08_L1TP_137024_20170829_20180524,Non-Glacier-Fed Lake,Altay and Sayan,201708,2229,124078.128077,1762.413093,18166.954159,98.7355734168674,52.5350034231929,"POLYGON ((-437798.546 5706275.081, -437859.297..."
1,2,GL098789E52521N,LC08_L1TP_137024_20170829_20180524,Glacier-Fed Lake,Altay and Sayan,201708,2510,43913.194543,834.398124,8600.975865,98.7890807043088,52.5210175897762,"POLYGON ((-434062.086 5704873.599, -434056.795..."

In [85]:
gdf_2020 = df5
gdf_2020.head(2)

,Source,Date,Area,Region,Type,Not_RGI,Error,Perimeter,Elevation,MG_ID1,MG_ID2,NewPro,geometry
0,p135r039_lc820190602,2019/06/02,0.071821,Nyainqentanglha,Pro-glacial lakes,NaN,0.016998,1133.210312,4218,RGI60-15.01107,NaN,NaN,"POLYGON ((49190.458 26227.206, 49176.699 26226..."
1,p147r035_lc820201014,2020/10/14,0.163401,Karakoram,Pro-glacial lakes,NaN,0.028043,1869.531406,5341,RGI60-14.05890,NaN,NaN,"POLYGON ((-1449015.43 786049.116, -1448993.205..."

In [86]:
import geopandas as gpd
import pandas as pd

# --- Your loaded layers ---
# gdf_2018  → has a glacial lake ID column, let's say it's called "gl_id"
# gdf_2020  → no ID yet

ID_COL = "GLAKE_ID"   # ← change to your actual column name in the 2018 layer
TARGET_CRS = "ESRI:102025"

# ── Step 1: Reproject both to equal-area ──────────────────────────────────
gdf_2018 = gdf_2018.to_crs(TARGET_CRS).reset_index(drop=True)
gdf_2020 = gdf_2020.to_crs(TARGET_CRS).reset_index(drop=True)

# Assign a temporary integer index to 2020 for tracking
gdf_2020["_idx_2020"] = gdf_2020.index
gdf_2018["_idx_2018"] = gdf_2018.index

# ── Step 2: Compute intersections ─────────────────────────────────────────
inter = gpd.overlay(
    gdf_2020[["_idx_2020", "geometry"]],
    gdf_2018[[ID_COL, "_idx_2018", "geometry"]],
    how="intersection",
    keep_geom_type=False
)

inter["overlap_area_m2"] = inter.geometry.area

# ── Step 3: For each 2020 polygon, keep the 2018 match with max overlap ───
best_match = (
    inter
    .sort_values("overlap_area_m2", ascending=False)
    .drop_duplicates(subset="_idx_2020", keep="first")   # one best match per 2020 lake
)

# ── Step 4: Overlap ratio filter (avoid spurious edge touches) ────────────
area_2020 = gdf_2020.set_index("_idx_2020").geometry.area
best_match["ref_area_m2"]   = best_match["_idx_2020"].map(area_2020)
best_match["overlap_ratio"] = best_match["overlap_area_m2"] / best_match["ref_area_m2"]

# Keep matches where at least 10% of the 2020 lake is covered by the 2018 polygon
# (stricter than before since these are close in time — only 2 years apart)
best_match = best_match[best_match["overlap_ratio"] >= 0.10]

print(f"2020 lakes total         : {len(gdf_2020)}")
print(f"Successfully matched     : {best_match['_idx_2020'].nunique()}")
print(f"Unmatched (new lakes?)   : {len(gdf_2020) - best_match['_idx_2020'].nunique()}")

# ── Step 5: Transfer the ID back to the 2020 layer ────────────────────────
id_map = best_match.set_index("_idx_2020")[ID_COL]

gdf_2020[ID_COL] = gdf_2020["_idx_2020"].map(id_map)
gdf_2020 = gdf_2020.drop(columns="_idx_2020")

# Flag unmatched lakes clearly
gdf_2020["id_source"] = gdf_2020[ID_COL].apply(
    lambda x: "matched_2018" if pd.notna(x) else "new_unmatched"
)

print(gdf_2020[ID_COL].isna().sum(), "lakes have no 2018 match (NaN id)")
print(gdf_2020.head())

# Save
gdf_2020.to_file("glacial_lakes_2020_with_id.gpkg", driver="GPKG")

2020 lakes total         : 9208
Successfully matched     : 6914
Unmatched (new lakes?)   : 2294
2294 lakes have no 2018 match (NaN id)
                 Source        Date      Area           Region  \
0  p135r039_lc820190602  2019/06/02  0.071821  Nyainqentanglha
1  p147r035_lc820201014  2020/10/14  0.163401        Karakoram
2  p147r035_lc820201014  2020/10/14  0.134054        Karakoram
3  p147r035_lc820201014  2020/10/14  0.068532        Karakoram
4  p147r036_lc820201014  2020/10/14  0.009101        Karakoram

                Type Not_RGI     Error    Perimeter  Elevation  \
0  Pro-glacial lakes     NaN  0.016998  1133.210312       4218
1  Pro-glacial lakes     NaN  0.028043  1869.531406       5341
2  Pro-glacial lakes     NaN  0.028617  1907.781731       5481
3  Pro-glacial lakes     NaN  0.018549  1236.586129       4556
4  Pro-glacial lakes     NaN  0.005504   366.947636       5592

           MG_ID1 MG_ID2                         NewPro  \
0  RGI60-15.01107    NaN                            NaN
1  RGI60-14.05890    NaN                            NaN
2  RGI60-14.07439    NaN  1990-2020 New Proglacial Lake
3  RGI60-14.07524    NaN                            NaN
4  RGI60-14.09085    NaN  1990-2020 New Proglacial Lake

                                            geometry         GLAKE_ID  \
0  POLYGON ((49190.458 26227.206, 49176.699 26226...              NaN
1  POLYGON ((-1449015.43 786049.116, -1448993.205...              NaN
2  POLYGON ((-1451727.298 790087.591, -1451747.14...              NaN
3  POLYGON ((-1484700.074 782331.377, -1484723.88...  GL077099E35395N
4  POLYGON ((-1387187.456 636757.873, -1387196.98...              NaN

       id_source
0  new_unmatched
1  new_unmatched
2  new_unmatched
3   matched_2018
4  new_unmatched

In [51]:
print(len(gdf_2018))

28953

In [87]:
gdf_2020.head()

,Source,Date,Area,Region,Type,Not_RGI,Error,Perimeter,Elevation,MG_ID1,MG_ID2,NewPro,geometry,GLAKE_ID,id_source
0,p135r039_lc820190602,2019/06/02,0.071821,Nyainqentanglha,Pro-glacial lakes,NaN,0.016998,1133.210312,4218,RGI60-15.01107,NaN,NaN,"POLYGON ((49190.458 26227.206, 49176.699 26226...",NaN,new_unmatched
1,p147r035_lc820201014,2020/10/14,0.163401,Karakoram,Pro-glacial lakes,NaN,0.028043,1869.531406,5341,RGI60-14.05890,NaN,NaN,"POLYGON ((-1449015.43 786049.116, -1448993.205...",NaN,new_unmatched
2,p147r035_lc820201014,2020/10/14,0.134054,Karakoram,Pro-glacial lakes,NaN,0.028617,1907.781731,5481,RGI60-14.07439,NaN,1990-2020 New Proglacial Lake,"POLYGON ((-1451727.298 790087.591, -1451747.14...",NaN,new_unmatched
3,p147r035_lc820201014,2020/10/14,0.068532,Karakoram,Pro-glacial lakes,NaN,0.018549,1236.586129,4556,RGI60-14.07524,NaN,NaN,"POLYGON ((-1484700.074 782331.377, -1484723.88...",GL077099E35395N,matched_2018
4,p147r036_lc820201014,2020/10/14,0.009101,Karakoram,Pro-glacial lakes,NaN,0.005504,366.947636,5592,RGI60-14.09085,NaN,1990-2020 New Proglacial Lake,"POLYGON ((-1387187.456 636757.873, -1387196.98...",NaN,new_unmatched

In [88]:
gdf_2020.dropna(subset=['GLAKE_ID'],inplace=True)

In [90]:
gdf_1990 = df1
gdf_2000 = df2
gdf_2010 = df3
gdf_2015 = df4

In [91]:
overlap_threshold = 0.10
years_hist = [1990,2000,2010,2015]

gdfs_hist = {
  1990:gdf_1990,
  2000:gdf_2000,
  2010:gdf_2010,
  2015:gdf_2015,
}

ref = gdf_2020.to_crs(TARGET_CRS).copy().reset_index(drop= True)
ref['_idx_ref'] = ref.index
ref['area_2020'] = ref.geometry.area
ref['perimeter_2020'] = ref.geometry.length
ref['geometry_2020'] = ref.geometry

master = ref.copy()

In [92]:
def match(ref_gdf,hist_gdf, year, threshold):
  hist = hist_gdf.to_crs(TARGET_CRS).copy().reset_index(drop = True)
  hist['_idx_hist'] = hist.index

  inter = gpd.overlay(
    ref_gdf[['_idx_ref','geometry']],
    hist[['_idx_hist','geometry']],
    how='intersection',
    keep_geom_type=False
  )

  if inter.empty:
    print(f'no overlaps found for {year}')
    return pd.DataFrame(columns=["_idx_ref",
                                     f"area_{year}",
                                     f"perimeter_{year}",
                                     f"geometry_{year}",
                                     f"flag_{year}"])
  

  inter['overlap_area_m2'] = inter.geometry.area
  best = (inter
          .sort_values('overlap_area_m2',ascending=False)
          .drop_duplicates(subset='_idx_ref',keep='first')
          .copy())
  
  ref_area_map = ref_gdf.set_index('_idx_ref')['area_2020']
  best['ref_area_m2'] = best['_idx_ref'].map(ref_area_map)
  best["overlap_ratio"] = best["overlap_area_m2"] / best["ref_area_m2"]
  best = best[best["overlap_ratio"] >= threshold].copy()

  hist['area_m2'] = hist.geometry.area
  hist['perim_m'] = hist.geometry.length
  hist['geom'] = hist.geometry

  hist_info = hist.set_index('_idx_hist')[['area_m2','perim_m','geom']]

  best[f'area_{year}'] = best['_idx_hist'].map(hist_info['area_m2'])
  best[f'perimeter_{year}'] = best['_idx_hist'].map(hist_info['perim_m'])
  best[f'geometry_{year}'] = best['_idx_hist'].map(hist_info['geom'])
  best[f'flag_{year}'] = 'observed'

  print(f' [{year}] matched: {len(best)} / {len(ref_gdf)}')

  return best[["_idx_ref",
                 f"area_{year}",
                 f"perimeter_{year}",
                 f"geometry_{year}",
                 f"flag_{year}"]].reset_index(drop=True)

In [93]:
for yr in years_hist:
  print(f'\nMatching {yr} -> 2020 ..')
  result = match(master, gdfs_hist[yr],yr,threshold = 0.10)


  if result.empty:
    master[f'area_{yr}'] = np.nan
    master[f'perimeter_{yr}'] = np.nan
    master[f'geometry_{yr}'] = np.nan
    master[f'flag_{yr}'] = 'not_mapped'
    continue

  master = master.merge(result, on= '_idx_ref',how = 'left')

Matching 1990 -> 2020 ..
 [1990] matched: 5488 / 6914

Matching 2000 -> 2020 ..
 [2000] matched: 5743 / 6914

Matching 2010 -> 2020 ..
 [2010] matched: 6024 / 6914

Matching 2015 -> 2020 ..
 [2015] matched: 6335 / 6914

In [111]:
all_years = [1990, 2000, 2010, 2015, 2020]

def first_observed_year(row):
    for yr in all_years:
        if yr == 2020:
            return 2020   # always observed in reference
        if pd.notna(row.get(f"area_{yr}")):
            return yr
    return 2020

master["first_observed_yr"] = master.apply(first_observed_year, axis=1)

# Now fill flags properly
for yr in years_hist:
    flag_col = f"flag_{yr}"
    area_col = f"area_{yr}"

    def fill_flag(row):
        if pd.notna(row[area_col]):
            return "observed"
        # NaN → decide why
        if row["first_observed_yr"] > yr:
            return "not_formed"    # lake formed after this year
        else:
            return "not_mapped"    # lake existed but missing from shapefile

    master[flag_col] = master.apply(fill_flag, axis=1)


# ── Step 5: Sanity check ──────────────────────────────────────────────────
print("\n── Flag summary ──")
for yr in years_hist:
    print(f"\n{yr}:")
    print(master[f"flag_{yr}"].value_counts())


# ── Step 6: Convert areas to km² ─────────────────────────────────────────
for yr in all_years:
    master[f"area_{yr}_km2"] = master[f"area_{yr}"] / 1e6


# ── Step 7: Compute expansion rate (observed points only) ─────────────────
def expansion_rate(row):
    obs_yrs   = []
    obs_areas = []

    for yr in all_years:
        flag = row.get(f"flag_{yr}", "observed")   # 2020 has no flag
        area = row.get(f"area_{yr}_km2", np.nan)
        if pd.notna(area) and flag == "observed":
            obs_yrs.append(yr)
            obs_areas.append(area)

    if len(obs_areas) < 2:
        return pd.Series({
            "expansion_rate_km2_yr" : np.nan,
            "expansion_rate_pct_yr" : np.nan,
            "n_obs_points"          : len(obs_areas)
        })

    slope, _ = np.polyfit(obs_yrs, obs_areas, 1)
    norm_rate = slope / obs_areas[0] * 100

    return pd.Series({
        "expansion_rate_km2_yr" : round(slope, 8),
        "expansion_rate_pct_yr" : round(norm_rate, 4),
        "n_obs_points"          : len(obs_areas)
    })

master[["expansion_rate_km2_yr",
        "expansion_rate_pct_yr",
        "n_obs_points"]] = master.apply(expansion_rate, axis=1)

# ── Step 8: Convert extra geometry columns to WKT before saving ───────────
output = gpd.GeoDataFrame(master, geometry="geometry_2020", crs=TARGET_CRS)
output = output.drop(columns=["_idx_ref"])

# Identify all extra geometry columns (all years except the active 2020)

── Flag summary ──

1990:
flag_1990
observed      5488
not_formed    1426
Name: count, dtype: int64

2000:
flag_2000
observed      5743
not_formed     963
not_mapped     208
Name: count, dtype: int64

2010:
flag_2010
observed      6024
not_formed     599
not_mapped     291
Name: count, dtype: int64

2015:
flag_2015
observed      6335
not_formed     333
not_mapped     246
Name: count, dtype: int64

In [112]:
from shapely.geometry.base import BaseGeometry

# Find ALL geometry-type columns except the active one
active_geom = output.geometry.name   # "geometry_2020"

def is_geom_column(series):
    """Check if a column contains geometry objects"""
    non_null = series.dropna()
    if len(non_null) == 0:
        return False
    return isinstance(non_null.iloc[0], BaseGeometry)

geom_cols_to_convert = [
    col for col in output.columns
    if col != active_geom and is_geom_column(output[col])
]

print(f"Converting these geometry columns to WKT: {geom_cols_to_convert}")

for col in geom_cols_to_convert:
    output[col] = gpd.GeoSeries(output[col], crs=TARGET_CRS).to_wkt()

# Verify no extra geometry columns remain
remaining = [col for col in output.columns
             if col != active_geom and is_geom_column(output[col])]
print(f"Remaining geometry columns after conversion: {remaining}")  # should be []

output.to_file("glacial_lakes_timeseries.gpkg", driver="GPKG")
print(f"Saved: {len(output)} lakes")

Converting these geometry columns to WKT: ['geometry', 'geometry_1990', 'geometry_2000', 'geometry_2010', 'geometry_2015']
Remaining geometry columns after conversion: []
Saved: 6914 lakes

In [110]:
output['geometry_2020']

0       POLYGON ((-1484700.074 782331.377, -1484723.88...
1       POLYGON ((-1415347.685 633371.82, -1415379.647...
2       POLYGON ((-1424755.132 650202.033, -1424761.53...
3       POLYGON ((-1425484.421 651570.284, -1425509.82...
4       POLYGON ((-1420641.234 663520.885, -1420661.34...
                              ...
6909    POLYGON ((-627799.854 -228367.919, -627817.845...
6910    POLYGON ((78158.046 -99.128, 78164.396 -121.35...
6911    POLYGON ((48902.591 26783.89, 48929.049 26772....
6912    POLYGON ((-72364.963 15316.305, -72369.726 153...
6913    POLYGON ((-1407124.133 209985.315, -1407116.19...
Name: geometry_2020, Length: 6914, dtype: geometry

In [113]:
import geopandas as gpd

# ── Load layers ───────────────────────────────────────────────────────────
lakes = gpd.read_file("glacial_lakes_timeseries.gpkg")   # polygon layer
glof  = gpd.read_file("model_data\shapefiles\glofs\glof.shp")                # point or polygon layer

print("GLOF geometry type :", glof.geom_type.unique())
print("Lakes geometry type:", lakes.geom_type.unique())
print("GLOF CRS :", glof.crs)
print("Lakes CRS:", lakes.crs)

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\3796110175.py:5: SyntaxWarning: invalid escape sequence '\s'
  glof  = gpd.read_file("model_data\shapefiles\glofs\glof.shp")                # point or polygon layer

GLOF geometry type : <StringArray>
['Point']
Length: 1, dtype: str
Lakes geometry type: <StringArray>
['MultiPolygon']
Length: 1, dtype: str
GLOF CRS : EPSG:4326
Lakes CRS: PROJCS["Asia_North_Albers_Equal_Area_Conic",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["latitude_of_center",30],PARAMETER["longitude_of_center",95],PARAMETER["standard_parallel_1",15],PARAMETER["standard_parallel_2",65],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["ESRI","102025"]]

In [116]:
# Reproject to same CRS
glof  = glof.to_crs(lakes.crs)

# Spatial join — each GLOF point gets the attributes of the lake it falls within
joined = gpd.sjoin(glof, lakes, how="inner", predicate="within")

print(f"Total GLOF events          : {len(glof)}")
print(f"GLOF events inside a lake  : {len(joined)}")
print(f"GLOF events outside lakes  : {len(glof) - len(joined)}")

# Count per lake
glof_per_lake = (joined
                 .groupby("GLAKE_ID")
                 .size()
                 .reset_index(name="glof_count")
                 .sort_values("glof_count", ascending=False))

print("\nTop lakes by GLOF count:")
print(glof_per_lake.head(10))

Total GLOF events          : 115
GLOF events inside a lake  : 45
GLOF events outside lakes  : 70

Top lakes by GLOF count:
           GLAKE_ID  glof_count
25  GL090325E28084N           2
14  GL086569E27826N           2
15  GL086586E27874N           2
38  GL096499E29465N           2
9   GL085850E28213N           2
0   GL071128E36474N           1
2   GL073359E36188N           1
1   GL072176E35781N           1
7   GL084631E28596N           1
6   GL082199E30309N           1

In [122]:
gl_1990 = gpd.read_file('1. glacial lake datasets\glacial_lakes_1990_v1.shp')
gl_2015 = gpd.read_file('1. glacial lake datasets\glacial_lakes_2015_v1.shp')

<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
<>:1: SyntaxWarning: invalid escape sequence '\g'
<>:2: SyntaxWarning: invalid escape sequence '\g'
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\2607986992.py:1: SyntaxWarning: invalid escape sequence '\g'
  gl_1990 = gpd.read_file('1. glacial lake datasets\glacial_lakes_1990_v1.shp')
C:\Users\rubel\AppData\Local\Temp\ipykernel_14308\2607986992.py:2: SyntaxWarning: invalid escape sequence '\g'
  gl_2015 = gpd.read_file('1. glacial lake datasets\glacial_lakes_2015_v1.shp')

In [124]:
# Timeseries analysis: gl_1990 and 5gl_2015 → combined GeoPackage
# (Similar workflow to glacial_lakes_timeseries.gpkg)

TARGET_CRS_GL = "ESRI:102025"

# ── Step 1: Use 2018 as reference, reproject both to equal-area ──────────
ref_gl = gl_2015.to_crs(TARGET_CRS_GL).reset_index(drop=True).copy()
ref_gl["_idx_ref"] = ref_gl.index
ref_gl["area_2015"] = ref_gl.geometry.area
ref_gl["perimeter_2015"] = ref_gl.geometry.length
ref_gl["geometry_2015"] = ref_gl.geometry

master_gl = ref_gl.copy()

# ── Step 2: Match 1990 to 2018 ────────────────────────────────────────────
hist_gl_1990 = gl_1990.to_crs(TARGET_CRS_GL).copy().reset_index(drop=True)
hist_gl_1990["_idx_hist"] = hist_gl_1990.index

inter_gl = gpd.overlay(
    ref_gl[["_idx_ref", "geometry"]],
    hist_gl_1990[["_idx_hist", "geometry"]],
    how="intersection",
    keep_geom_type=False
)

overlap_threshold = 0.10

if not inter_gl.empty:
    inter_gl["overlap_area_m2"] = inter_gl.geometry.area
    best_gl = (
        inter_gl
        .sort_values("overlap_area_m2", ascending=False)
        .drop_duplicates(subset="_idx_ref", keep="first")
        .copy()
    )
    
    ref_area_map_gl = ref_gl.set_index("_idx_ref")["area_2015"]
    best_gl["ref_area_m2"] = best_gl["_idx_ref"].map(ref_area_map_gl)
    best_gl["overlap_ratio"] = best_gl["overlap_area_m2"] / best_gl["ref_area_m2"]
    best_gl = best_gl[best_gl["overlap_ratio"] >= overlap_threshold].copy()
    
    hist_gl_1990["area_m2"] = hist_gl_1990.geometry.area
    hist_gl_1990["perim_m"] = hist_gl_1990.geometry.length
    hist_gl_1990["geom"] = hist_gl_1990.geometry
    
    hist_info_gl = hist_gl_1990.set_index("_idx_hist")[["area_m2", "perim_m", "geom"]]
    
    best_gl["area_1990"] = best_gl["_idx_hist"].map(hist_info_gl["area_m2"])
    best_gl["perimeter_1990"] = best_gl["_idx_hist"].map(hist_info_gl["perim_m"])
    best_gl["geometry_1990"] = best_gl["_idx_hist"].map(hist_info_gl["geom"])
    best_gl["flag_1990"] = "observed"
    
    result_gl = best_gl[
        ["_idx_ref", "area_1990", "perimeter_1990", "geometry_1990", "flag_1990"]
    ].reset_index(drop=True)
    
    master_gl = master_gl.merge(result_gl, on="_idx_ref", how="left")
    print(f"[1990] matched: {len(result_gl)} / {len(master_gl)}")
else:
    print("No overlaps found for 1990")
    master_gl["area_1990"] = np.nan
    master_gl["perimeter_1990"] = np.nan
    master_gl["geometry_1990"] = np.nan
    master_gl["flag_1990"] = "not_mapped"

# ── Step 3: Fill flags ────────────────────────────────────────────────────
all_years_gl = [1990, 2015]

def first_observed_year_gl(row):
    for yr in all_years_gl:
        if yr == 2015:
            return 2015
        if pd.notna(row.get(f"area_{yr}")):
            return yr
    return 2015

master_gl["first_observed_yr"] = master_gl.apply(first_observed_year_gl, axis=1)

flag_col = "flag_1990"
area_col = "area_1990"

def fill_flag_gl(row):
    if pd.notna(row[area_col]):
        return "observed"
    if row["first_observed_yr"] > 1990:
        return "not_formed"
    else:
        return "not_mapped"

master_gl[flag_col] = master_gl.apply(fill_flag_gl, axis=1)

print("\n── Flag summary ──")
print(f"1990: {master_gl['flag_1990'].value_counts().to_dict()}")

# ── Step 4: Convert to km² ────────────────────────────────────────────────
for yr in all_years_gl:
    master_gl[f"area_{yr}_km2"] = master_gl[f"area_{yr}"] / 1e6

# ── Step 5: Compute expansion rate ────────────────────────────────────────
def expansion_rate_gl(row):
    obs_yrs = []
    obs_areas = []
    
    for yr in all_years_gl:
        flag = row.get(f"flag_{yr}", "observed")
        area = row.get(f"area_{yr}_km2", np.nan)
        if pd.notna(area) and flag == "observed":
            obs_yrs.append(yr)
            obs_areas.append(area)
    
    if len(obs_areas) < 2:
        return pd.Series({
            "expansion_rate_km2_yr": np.nan,
            "expansion_rate_pct_yr": np.nan,
            "n_obs_points": len(obs_areas)
        })
    
    slope, _ = np.polyfit(obs_yrs, obs_areas, 1)
    norm_rate = slope / obs_areas[0] * 100
    
    return pd.Series({
        "expansion_rate_km2_yr": round(slope, 8),
        "expansion_rate_pct_yr": round(norm_rate, 4),
        "n_obs_points": len(obs_areas)
    })

master_gl[["expansion_rate_km2_yr", "expansion_rate_pct_yr", "n_obs_points"]] = master_gl.apply(
    expansion_rate_gl, axis=1
)

# ── Step 6: Convert extra geometry columns to WKT ─────────────────────────
output_gl = gpd.GeoDataFrame(master_gl, geometry="geometry_2015", crs=TARGET_CRS_GL)
output_gl = output_gl.drop(columns=["_idx_ref"])

# Find all geometry columns to convert
active_geom_gl = output_gl.geometry.name

geom_cols_to_convert_gl = [
    col for col in output_gl.columns
    if col != active_geom_gl and is_geom_column(output_gl[col])
]

print(f"Converting geometry columns to WKT: {geom_cols_to_convert_gl}")

for col in geom_cols_to_convert_gl:
    output_gl[col] = gpd.GeoSeries(output_gl[col], crs=TARGET_CRS_GL).to_wkt()

# ── Step 7: Save ──────────────────────────────────────────────────────────
output_gl.to_file("glacial_lakes_1990_2015_timeseries.gpkg", driver="GPKG")
print(f"Saved: {len(output_gl)} lakes to glacial_lakes_1990_2015_timeseries.gpkg")

[1990] matched: 22680 / 26634

── Flag summary ──
1990: {'observed': 22680, 'not_formed': 3954}
Converting geometry columns to WKT: ['geometry', 'geometry_1990']
Saved: 26634 lakes to glacial_lakes_1990_2015_timeseries.gpkg